### ISSUE TITLE
Installation problems Ubuntu

### ISSUE THREAD

**Issue by alexarje** [cpmpercussion/myo-to-osc#7]
Tried to install on Ubuntu 17.10. Running `pip3 install requirements.txt` results in the error message: 

> Could not find a version that satisfies the requirement requirements.txt (from versions: )
> No matching distribution found for requirements.txt

Perhaps something wrong with the way command there? When I tried to install the requirements separately, pyserial installs fine, but there does not seem to be a version for pythonosc. Should it be python-osc? At least there is a package called that, and the following command works fine: `pip3 install pyserial python-osc`.

**Comment by cpmpercussion** [comment]
Whoops! just an oversight about the instructions, it should be `pip3 install -r requirements.txt` to install from the requirements file and the module's package name is as `python-osc`.
